name = "ubiquity-os-command-wallet"
main = "src/worker.ts"
compatibility_date = "2025-11-01"
compatibility_flags = [ "nodejs_compat" ]
[env.dev]
[env.prod]

[observability]
enabled = true

[version_metadata]
binding = "CLOUDFLARE_VERSION_METADATA"