name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:
  delete:

jobs:
  update-manifest:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Update Manifest and Commit Changes
        uses: Meniole/action-deploy-plugin@feat/320-dist-artifact-branches
        with:
          action: ${{ github.event_name == 'delete' && 'delete' || 'publish' }}
          sourceRef: ${{ github.event.ref || github.event.workflow_run.head_branch || github.ref_name }}
          artifactPrefix: dist/
          treatAsEsm: false
          sourcemap: false
          pluginEntry: ${{ github.workspace }}/src/main.ts
          excludeSupportedEvents: "issue_comment.created"
          skipBotEvents: false
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
